package com.example.kotlinpractice.extensions
/*
    - This file contains example of extension functions.
    - It also shows that extensions are statically resolved .
 */
fun main() {

    val perform = Calculator(30, 15)
    println(perform.addition()) //prints 45
    perform.divide() // prints Result of division is 2 and is generated by extension function

    val bus = Bus()
    getVehicle(bus) // prints Vehicle is running
}

class Calculator(val a: Int, val b: Int) {
    fun addition() = a + b
    fun multiply() = a * b
    fun substract() = a - b
}

fun Calculator.divide() {
    println("Result of division is ${a / b} and is generated by extension function  ")
}

//static resolution of extension functions
open class Vehicle {
    val vehicleNumber: Int = 3000
}

class Bus : Vehicle() {
    fun journeyTo() = println("The bus is going from surat to ahmedabad")
}

fun Vehicle.run() = println("Vehicle is running")

fun Bus.run() = println("Bus is running")

fun getVehicle(v: Vehicle) = v.run()